on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{secrets.GITHUB_TOKEN}}" | podman login -u "${{github.actor}}" --password-stdin ghcr.io
      - run: podman build --no-cache -t "ghcr.io/charles25565/tribbleproxy:latest" .
      - run: podman push "ghcr.io/charles25565/tribbleproxy:latest"
        if: github.event_name != 'pull_request'